import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import '../styles/theme.css';
import QueryProvider from '@/lib/query-provider';
import { Toaster } from 'sonner';

export const fontPoppins = Poppins({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: '--font-poppins',
});

export const metadata: Metadata = {
	title: 'Gold & Pepper',
	description: 'Generated by create next app',
};

export default function DefaultLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${fontPoppins.variable} scrollbar-body`}>
				<QueryProvider>{children}</QueryProvider>
				<Toaster richColors className="font-poppins" />
			</body>
		</html>
	);
}
